window.PORTAL_DATA = {
  "summary": {
    "identified": 134,
    "contacted": 124,
    "responded": 23,
    "interested": 6,
    "declined": 17,
    "nda": 2,
    "infoReceived": 0,
    "lastUpdated": "16 de julio de 2026"
  },
  "companies": [
    {
      "id": 1,
      "name": "Abarroteras La Abeja",
      "industry": "Distribución",
      "subindustry": "Mayoreo de abarrotes",
      "location": "Guadalajara",
      "website": "https://www.abarrotesabeja.com/",
      "description": "Distribuye abarrotes y productos de consumo para comercios y mayoristas.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 2,
      "name": "Barrinolas",
      "industry": "Manufactura",
      "subindustry": "Alimentos saludables y snacks",
      "location": "Zapopan",
      "website": "https://barrinolas.com/",
      "description": "Produce botanas y snacks tradicionales para el mercado nacional.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Interés",
      "status": "Interés confirmado | NDA firmado y pendiente recepción de información",
      "information": "Pendiente",
      "nextStep": "Seguimiento para recibir información"
    },
    {
      "id": 3,
      "name": "Benmart AG",
      "industry": "Manufactura",
      "subindustry": "Superfoods e ingredientes alimenticios",
      "location": "Tlaquepaque",
      "website": "https://benmart.mx/",
      "description": "Produce, comercializa y exporta superfoods, ingredientes naturales y alimentos saludables, además de ofrecer servicios de envasado y acondicionamiento para la industria alimentaria.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 4,
      "name": "Cajas Plegadizas de Occidente (Cartoimagen)",
      "industry": "Manufactura",
      "subindustry": "Empaque plegadizo",
      "location": "Zapopan",
      "website": "https://cartoimagen.com.mx/",
      "description": "Fabrica empaques de cartón plegadizo e impresión para productos de consumo.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 5,
      "name": "Aceros Coyote S.A. de C.V.",
      "industry": "Distribución",
      "subindustry": "Aceros y metales especiales",
      "location": "Tlaquepaque",
      "website": "https://aceroscoyote.com/",
      "description": "Comercialización y procesamiento de aceros/metales especiales; ubicada en Álamo Industrial.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 6,
      "name": "Corrugados de Occidente",
      "industry": "Manufactura",
      "subindustry": "Empaque de cartón corrugado",
      "location": "Tlaquepaque",
      "website": "https://www.corrugadosdeoccidente.com/",
      "description": "Fabrica cajas y soluciones de empaque de cartón corrugado.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 7,
      "name": "Dilox",
      "industry": "Manufactura",
      "subindustry": "Alimentos porcionados",
      "location": "El Salto",
      "website": "https://picalsa.dilox.com.mx/inicio",
      "description": "Fabrica y envasa alimentos, condimentos, salsas e ingredientes en presentaciones porcionadas para las industrias de foodservice, hospitalidad y alimentos preparados",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Interés",
      "status": "Interés confirmado | En espera de decisión de accionistas​",
      "information": "Pendiente",
      "nextStep": "Seguimiento para recibir respuesta"
    },
    {
      "id": 8,
      "name": "Distribuidora La Abundancia",
      "industry": "Distribución",
      "subindustry": "Mayoreo de abarrotes",
      "location": "Guadalajara",
      "website": "https://www.labundancia.com/",
      "description": "Distribuye alimentos, abarrotes y productos de consumo al mayoreo.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 9,
      "name": "Valcon",
      "industry": "Manufactura",
      "subindustry": "Fundición y maquinado",
      "location": "Tlaquepaque",
      "website": "https://valcon.mx/",
      "description": "Fabrica y maquila piezas fundidas y maquinadas en hierro y acero para aplicaciones industriales.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 10,
      "name": "Embamar Packaging Technology",
      "industry": "Manufactura",
      "subindustry": "Embalaje industrial",
      "location": "Guadalajara",
      "website": "https://www.embamar.com/",
      "description": "Diseña y fabrica maquinaria y soluciones tecnológicas para procesos de empaque.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 11,
      "name": "Emypla",
      "industry": "Manufactura",
      "subindustry": "Empaque plástico",
      "location": "Tlajomulco",
      "website": "https://www.emypla.com.mx",
      "description": "Fabrica películas plásticas y materiales para embalaje industrial.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 12,
      "name": "Empropack Empaques Profesionales S.A. de C.V.",
      "industry": "Distribución",
      "subindustry": "Empaque y embalaje",
      "location": "Tlaquepaque",
      "website": "https://empropack.com/",
      "description": "Comercializa soluciones de empaque industrial y materiales de embalaje.",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 13,
      "name": "En-Trega",
      "industry": "Logística",
      "subindustry": "Paquetería y mensajería",
      "location": "Zapopan",
      "website": "https://www.en-trega.com/",
      "description": "Ofrece servicios de logística, mensajería y distribución de mercancías.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 14,
      "name": "Almet Indsutrial",
      "industry": "Manufactura",
      "subindustry": "Maquinados CNC y fabricación metálica",
      "location": "Guadalajara",
      "website": "https://www.almetindustrial.com/",
      "description": "Empresa especializada en fabricación de piezas metálicas de precisión, maquinados CNC, soldadura y ensambles industriales",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 15,
      "name": "Grupo Pack System",
      "industry": "Manufactura",
      "subindustry": "Maquinaria para empaque",
      "location": "Tlajomulco",
      "website": "https://packsystem.com.mx/",
      "description": "Integra maquinaria, equipos y materiales para líneas de empaque.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 16,
      "name": "Grupo Prologiss",
      "industry": "Logística",
      "subindustry": "Logística y almacenaje",
      "location": "Guadalajara",
      "website": "https://grupoprologiss.com.mx/",
      "description": "Ofrece servicios de logística, almacenaje y distribución para empresas.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 17,
      "name": "Boli Bolsas",
      "industry": "Manufactura",
      "subindustry": "Bolsas plásticas",
      "location": "Guadalajara",
      "website": "https://www.boli-bolsas.com/",
      "description": "Fabrica bolsas de plástico y soluciones de empaque flexible para uso comercial e industrial.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 18,
      "name": "Borse Winsnes",
      "industry": "Manufactura",
      "subindustry": "Bolsas",
      "location": "Guadalajara",
      "website": "https://borse.com.mx/",
      "description": "Fabrica bolsas personalizadas de papel, plástico y tela para aplicaciones comerciales, promocionales y de retail.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 19,
      "name": "Grupo Textil Román",
      "industry": "Manufactura",
      "subindustry": "Textil",
      "location": "Guadalajara",
      "website": "https://grupotextilroman.com/",
      "description": "Fabrica uniformes, prendas industriales y textiles personalizados.",
      "method": "Llamada",
      "firstContact": "2026-07-14",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 20,
      "name": "Cintas y Especialidades Impresas S.A. de C.V.",
      "industry": "Manufactura",
      "subindustry": "Etiquetas",
      "location": "Zapopan",
      "website": "https://cei-cei.com.mx/",
      "description": "Produce etiquetas, cintas impresas y soluciones de identificación para empaque.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 21,
      "name": "Innobags",
      "industry": "Manufactura",
      "subindustry": "Empaque flexible",
      "location": "Zapopan",
      "website": "https://innobags.com.mx/",
      "description": "Desarrolla y fabrica bolsas y empaques flexibles personalizados.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 22,
      "name": "Lacta Ingredientes",
      "industry": "Manufactura",
      "subindustry": "Ingredientes lácteos",
      "location": "Zapopan",
      "website": "https://lacta.mx/",
      "description": "Distribuye ingredientes lácteos y materias primas para alimentos y bebidas.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Rechazo",
      "status": "No tienen interés por vender en este momento.",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 23,
      "name": "Manufacturas Pueblo Viejo Industrial S.A. de C.V.",
      "industry": "Manufactura",
      "subindustry": "Empaque flexible",
      "location": "Guadalajara",
      "website": "N/A",
      "description": "Fabrica componentes metálicos y productos para aplicaciones industriales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 24,
      "name": "Multiplastic",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Tlajomulco",
      "website": "https://www.multiplastic.com.mx/",
      "description": "Fabrica productos plásticos y soluciones de transformación para la industria.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 25,
      "name": "Okko Superfoods",
      "industry": "Manufactura",
      "subindustry": "Superfoods e ingredientes funcionales",
      "location": "Tlajomulco",
      "website": "https://okkosuperfoods.com/",
      "description": "Desarrolla alimentos saludables y productos funcionales.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 26,
      "name": "Pepitoria Sinaloense",
      "industry": "Manufactura",
      "subindustry": "Botanas",
      "location": "Guadalajara",
      "website": "https://www.pepitorias.com.mx/",
      "description": "Produce botanas tradicionales elaboradas a base de semillas.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 27,
      "name": "Precision Metal Stamping (PM Stamping)",
      "industry": "Manufactura",
      "subindustry": "Estampado metálico",
      "location": "Tlaquepaque",
      "website": "https://pmstamping.com/",
      "description": "Fabrica componentes metálicos mediante procesos de estampado de precisión.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 28,
      "name": "Proanka Alimentos",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Zapopan",
      "website": "https://proankaalimentos.com/",
      "description": "Fabrica alimentos procesados y productos listos para consumo.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 29,
      "name": "Prodeyma",
      "industry": "Manufactura",
      "subindustry": "Ingredientes alimenticios",
      "location": "Zapopan",
      "website": "https://www.prodeyma.com/",
      "description": "Brinda servicios de maquila, procesamiento y envasado de granos, cereales e ingredientes alimenticios para marcas propias y terceros",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 30,
      "name": "Dicatex",
      "industry": "Distribución",
      "subindustry": "Telas de tapicería",
      "location": "Guadalajara",
      "website": "https://www.dicatex.mx/",
      "description": "Comercializa telas de tapicería para muebles y decoración",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 31,
      "name": "Productos Don Elías",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Zapopan",
      "website": "https://productosdonelias.com/site/",
      "description": "Elabora alimentos tradicionales y conservas para el mercado nacional.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 32,
      "name": "SABROSAM",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Guadalajara",
      "website": "https://sabrosam.com/",
      "description": "Produce salsas, condimentos y alimentos procesados.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 33,
      "name": "ST Plastic",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Zapopan",
      "website": "https://stplastic.mx/",
      "description": "Fabrica productos plásticos y soluciones de transformación para la industria.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Interés",
      "status": "Interés confirmado | En espera de decisión de accionistas​",
      "information": "Pendiente",
      "nextStep": "Seguimiento para recibir respuesta"
    },
    {
      "id": 34,
      "name": "Tecniplast Mexico",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Zapopan",
      "website": "https://tecniplastmexico.com/web/",
      "description": "Fabrica piezas y componentes plásticos para aplicaciones industriales.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 35,
      "name": "Tecnometal",
      "industry": "Manufactura",
      "subindustry": "Productos metálicos",
      "location": "Tlaquepaque",
      "website": "http://tecnometal.org/es/index.html",
      "description": "Fabrica estructuras, componentes y soluciones metalmecánicas.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 36,
      "name": "Diseños de Cartón",
      "industry": "Manufactura",
      "subindustry": "Empaque de cartón",
      "location": "Guadalajara",
      "website": "https://disenosdecarton.miadn.mx/",
      "description": "Fabrica empaques, exhibidores y productos de cartón personalizados.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 37,
      "name": "Divisiones y Corrugadores",
      "industry": "Manufactura",
      "subindustry": "Empaque de cartón corrugado",
      "location": "Guadalajara",
      "website": "https://www.divisionesycorrugados.com.mx/",
      "description": "Fabrica divisiones, separadores y empaques de cartón corrugado para la protección y transporte de productos.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 38,
      "name": "Torninox",
      "industry": "Distribución",
      "subindustry": "Ferretería y suministros industriales",
      "location": "Guadalajara",
      "website": "https://www.torninox.com/",
      "description": "Distribuye tornillería y productos de acero inoxidable para aplicaciones industriales.",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 39,
      "name": "Tostadas Tricas",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Zapopan",
      "website": "https://tricas.com.mx/",
      "description": "Produce tostadas, botanas y alimentos derivados del maíz.",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 40,
      "name": "TotoFast",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Zapopan",
      "website": "https://www.totofast.com/",
      "description": "Fabrica alimentos preparados y productos listos para consumo.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 41,
      "name": "Envases Val",
      "industry": "Manufactura",
      "subindustry": "Envases plásticos",
      "location": "Guadalajara",
      "website": "https://www.envasesval.mx/",
      "description": "Fabrica envases y recipientes plásticos para diversas industrias.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 42,
      "name": "Fabrica de Hielo en Guadalajara Club Ice",
      "industry": "Manufactura",
      "subindustry": "Fabricación y distribución de hielo",
      "location": "Zapopan",
      "website": "https://www.clubice.mx/",
      "description": "Empresa familiar con mas de 30 años en fabricación y distribución de hielo en Occidente.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 43,
      "name": "Alamo Aluminios",
      "industry": "Distribución",
      "subindustry": "Perfiles de aluminio y acero",
      "location": "Zapopan",
      "website": "https://alamoaluminios.com/",
      "description": "Distribuye perfiles de aluminio, acero y herrajes para construcción",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 44,
      "name": "Perisur Grupo Ferretero",
      "industry": "Distribución",
      "subindustry": "Mayoreo de ferretería",
      "location": "Tlaquepaque",
      "website": "https://www.gfperisur.com.mx/",
      "description": "Comercializa artículos ferreteros al mayoreo para negocios y constructoras",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 45,
      "name": "Roca Distribuciones",
      "industry": "Distribución",
      "subindustry": "Mayoreo de artículos para el hogar",
      "location": "Guadalajara",
      "website": "https://sites.google.com/view/rocadistribucionesgdlcom/p%C3%A1gina-principal",
      "description": "Importa y distribuye artículos para el hogar a mayoreo",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 46,
      "name": "Sigma Pegamentos",
      "industry": "Manufactura",
      "subindustry": "Adhesivos industriales",
      "location": "Guadalajara",
      "website": "https://www.sigmapegamentos.com/",
      "description": "Fabrica y distribuye pegamentos especializados",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 47,
      "name": "Flavors CGV Internacional S.A. de C.V.",
      "industry": "Manufactura",
      "subindustry": "Saborizantes y colorantes alimenticios",
      "location": "Tlaquepaque",
      "website": "https://flavorscgv.com/",
      "description": "Desarrolla sabores e ingredientes para la industria de alimentos y bebidas.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 48,
      "name": "Viaggi Transportes",
      "industry": "Logística",
      "subindustry": "Paquetería y carga consolidada",
      "location": "Guadalajara",
      "website": "https://www.viaggitransportes.com.mx/",
      "description": "Ofrece transportación y paquetería con cobertura en Occidente de México",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 49,
      "name": "Dimabsa",
      "industry": "Distribución",
      "subindustry": "Mangueras y conexiones industriales",
      "location": "Guadalajara",
      "website": "https://dimabsa.mx/",
      "description": "Distribuye mangueras, conexiones y conexiones industriales",
      "method": "Llamada",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 50,
      "name": "Caslon",
      "industry": "Manufactura",
      "subindustry": "Pinturas y recubrimientos",
      "location": "Guadalajara",
      "website": "https://www.caslon.com.mx/",
      "description": "Fabrica y comercializa resinas y recubrimientos industriales",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 51,
      "name": "Grupo Dulcero Tarahumara",
      "industry": "Distribución",
      "subindustry": "Confitería y dulces",
      "location": "Guadalajara",
      "website": "https://grupodulcerotarahumara.miadn.mx/",
      "description": "Distribuye dulces, botanas y productos de confitería para el canal mayorista.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 52,
      "name": "Auto Express 24 Horas",
      "industry": "Logística",
      "subindustry": "Carga consolidada y paquetería",
      "location": "Guadalajara",
      "website": "https://www.autoexpress24horas.com/",
      "description": "Transporta carga consolidada y paquetería",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 53,
      "name": "Ulsa Tech",
      "industry": "Manufactura",
      "subindustry": "Farmacéuticos oncológicos",
      "location": "Guadalajara",
      "website": "https://ulsatech.com.mx/",
      "description": "Fabrica y comercializa productos farmacéuticos de especialidad oncológica",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 54,
      "name": "Tuberias Visa de Guadalajara",
      "industry": "Distribución",
      "subindustry": "Tubería, válvulas y conexiones",
      "location": "Guadalajara",
      "website": "https://visaguadalajara.com/",
      "description": "Suministra tubería, válvulas y conexiones en acero con asesoría técnica",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 55,
      "name": "Fletes de Oriente",
      "industry": "Logística",
      "subindustry": "Transporte de carga terrestre",
      "location": "Guadalajara",
      "website": "https://www.fletesdeoriente.com/",
      "description": "Transporta mercancía vía terrrestre con cobertura nacional",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 56,
      "name": "Groppe Imprenta",
      "industry": "Manufactura",
      "subindustry": "Impresión digital de bajo volumen",
      "location": "Guadalajara",
      "website": "https://groppeimprenta.com/",
      "description": "Fabrica llibros y material impreso en bajo volumen",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 57,
      "name": "Raziio",
      "industry": "Infraestructura",
      "subindustry": "Sistemas de drenaje pluvial e hidráulico",
      "location": "Guadalajara",
      "website": "https://raziio.com/",
      "description": "Distribuye e integra sistemas prefabricados de drenaje pluvial, captación de agua y soluciones hidráulicas para proyectos de infraestructura y construcción.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 58,
      "name": "Grupo Rago",
      "industry": "Distribución",
      "subindustry": "Maquinaria",
      "location": "Guadalajara",
      "website": "https://www.gruporago.com/",
      "description": "Distribuidor y proveedor de equipos de bombeo y soluciones para el manejo de agua, con servicios de instalación, mantenimiento y reparación.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 59,
      "name": "Grupo Soporte e Ingredientes Mexico (GSI Mexico)",
      "industry": "Manufactura",
      "subindustry": "Ingredientes y aditivos alimenticios",
      "location": "Tlaquepaque",
      "website": "http://gsi-ingredientes.com.mx/",
      "description": "Distribuye ingredientes y materias primas para la industria alimentaria.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 60,
      "name": "Garanti Autoparts",
      "industry": "Distribución",
      "subindustry": "Autopartes",
      "location": "Guadalajara",
      "website": "https://www.garantiautoparts.com/ecommerce/",
      "description": "Distribuye y comercializa refacciones automotrices para vehículos ligeros y de trabajo.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 61,
      "name": "Grey Forestal",
      "industry": "Distribución",
      "subindustry": "Productos forestales y maderas",
      "location": "Guadalajara",
      "website": "https://greyforestal.com/",
      "description": "Importa y distribuye maderas, tableros y productos forestales para la industria mueblera y de la construcción.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 62,
      "name": "Gummy Life",
      "industry": "Manufactura",
      "subindustry": "Confitería",
      "location": "Zapopan",
      "website": "https://www.gummylife.mx",
      "description": "Produce suplementos alimenticios en formato de gomitas funcionales.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 63,
      "name": "Operadora Palermo",
      "industry": "Logística",
      "subindustry": "Transporte de carga y logística",
      "location": "Guadalajara",
      "website": "https://operadorapalermo.com.mx/",
      "description": "Proporciona servicios de transporte terrestre de carga, logística y distribución de mercancías.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 64,
      "name": "Power Depot",
      "industry": "Distribución",
      "subindustry": "Material eléctrico y soluciones de energía",
      "location": "Guadalajara",
      "website": "https://powerdepot.com.mx/",
      "description": "Distribuye material eléctrico, equipos de respaldo de energía, iluminación y soluciones para infraestructura eléctrica.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 65,
      "name": "Imprimatur Acabados",
      "industry": "Manufactura",
      "subindustry": "Empaque e impresión",
      "location": "Guadalajara",
      "website": "https://imprimatur.com.mx/",
      "description": "Fabrica empaques de cartón plegadizo e impresos comerciales para diversas industrias.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 66,
      "name": "Surtimex",
      "industry": "Distribución",
      "subindustry": "Mayoreo de abarrotes y consumo",
      "location": "Guadalajara",
      "website": "https://www.surtimex.com/",
      "description": "Distribuye productos de abarrotes, alimentos y artículos de consumo para mayoristas y comercios.",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 67,
      "name": "Lubtrac",
      "industry": "Distribución",
      "subindustry": "Lubricantes industriales y automotrices",
      "location": "Zapopan",
      "website": "https://www.lubtrac.com.mx/",
      "description": "Distribuye lubricantes, grasas, filtros y productos especializados para la industria y el transporte.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 68,
      "name": "Ipisa",
      "industry": "Distribución",
      "subindustry": "Pinturas y recubrimientos",
      "location": "Zapopan",
      "website": "https://ipisa.miadn.mx/",
      "description": "Distribuye pinturas, recubrimientos y productos complementarios para los sectores industrial y arquitectónico.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 69,
      "name": "JR Paquetería",
      "industry": "Logística",
      "subindustry": "Paquetería y mensajería",
      "location": "Tlaquepaque",
      "website": "https://jrpaqueteria.mx/",
      "description": "Proporciona servicios de paquetería, mensajería y carga consolidada con cobertura en gran parte de México.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 70,
      "name": "BIme Seguridad Industrial",
      "industry": "Distribución",
      "subindustry": "Equipo de seguridad industrial",
      "location": "Guadalajara",
      "website": "https://www.bimeseguridadindustrial.com/",
      "description": "Distribuye equipo de protección personal (EPP), señalización y productos para seguridad industrial.",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 71,
      "name": "Uniformes Paquirri",
      "industry": "Manufactura",
      "subindustry": "Uniformes industriales",
      "location": "Guadalajara",
      "website": "https://www.uniformespaquirri.com.mx/",
      "description": "Confecciona y comercializa uniformes empresariales, escolares e industriales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 72,
      "name": "KO Solar",
      "industry": "Distribución",
      "subindustry": "Sistemas fotovoltaicos y Energía",
      "location": "Tlaquepaque",
      "website": "https://kosolar.mx/",
      "description": "Venta e instalación de paneles solares para hogares y negocios.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 73,
      "name": "Multiempack",
      "industry": "Manufactura",
      "subindustry": "Empaque de cartón corrugado",
      "location": "Zapopan",
      "website": "https://www.cartonmemultiempack.com/",
      "description": "Fabrica cajas, empaques y soluciones de cartón corrugado para la industria.",
      "method": "Llamada",
      "firstContact": "",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 74,
      "name": "Exi",
      "industry": "Distribución",
      "subindustry": "Empaque industrial",
      "location": "Guadalajara",
      "website": "https://www.exiguadalajara.com/",
      "description": "Distribuye materiales y suministros de empaque para clientes industriales y comerciales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 75,
      "name": "Fase Industrial",
      "industry": "Manufactura",
      "subindustry": "Hules y recubrimientos industriales",
      "location": "Guadalajara",
      "website": "https://www.hulesdeingenieriayrecubrimientos.com/",
      "description": "Fabrica piezas de hule, recubrimientos y componentes para aplicaciones industriales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 76,
      "name": "Montenegro",
      "industry": "Manufactura",
      "subindustry": "Edición de material educativo",
      "location": "Guadalajara",
      "website": "https://montenegroeditores.com.mx/inicio/inicio",
      "description": "Crea, edita e imprime contenido educativo para maestros y alumnos",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 77,
      "name": "Transportes Foráneos González",
      "industry": "Logística",
      "subindustry": "Transporte de carga terrestre",
      "location": "Guadalajara",
      "website": "https://www.transportesforaneosgonzalez.com/",
      "description": "Proporciona servicios de transporte foráneo de carga y logística nacional.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 78,
      "name": "Bolsas y Empaques Ceja",
      "industry": "Distribución",
      "subindustry": "Empaques flexibles y desechables",
      "location": "Guadalajara",
      "website": "https://www.bolsasyempaquesceja.com/",
      "description": "Distribuye bolsas, empaques y artículos desechables para la industria y el comercio.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 79,
      "name": "Panel W",
      "industry": "Distribución",
      "subindustry": "Paneles y materiales de construcción",
      "location": "Guadalajara",
      "website": "https://panelw.com/",
      "description": "Comercializa panel aislante y materiales para construcción industrial y comercial.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 80,
      "name": "Indpack",
      "industry": "Manufactura",
      "subindustry": "Empaque industrial",
      "location": "Zapopan",
      "website": "https://indpack-jalisco.miadn.mx/",
      "description": "Fabrica soluciones de empaque industrial y materiales de protección para productos.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 81,
      "name": "Plásticos San Isidro",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Zapopan",
      "website": "https://www.plasticossanisidro.com.mx/",
      "description": "Fabrica envases, piezas y productos plásticos para aplicaciones industriales y comerciales.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 82,
      "name": "Maderas y Tarimas Madytar",
      "industry": "Manufactura",
      "subindustry": "Tarimas y embalaje de madera",
      "location": "Guadalajara",
      "website": "https://maderasytarimasmadytar.miadn.mx/",
      "description": "Fabrica tarimas, embalajes y productos de madera para logística e industria.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 83,
      "name": "Proveedora Malber",
      "industry": "Distribución",
      "subindustry": "Suministros industriales",
      "location": "Zapopan",
      "website": "https://www.proveedoramalber.com/",
      "description": "Distribuye insumos, materiales y productos para clientes industriales y comerciales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 84,
      "name": "Plásticos Santa Lucía",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Zapopan",
      "website": "https://www.plasticos-santa-lucia.com/",
      "description": "Fabrica envases y productos plásticos para aplicaciones industriales y de consumo.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 85,
      "name": "Polímeros Tapatios",
      "industry": "Manufactura",
      "subindustry": "Plasticos y empaques",
      "location": "Guadalajara",
      "website": "https://polimerostapatios.com/",
      "description": "Fabricación y comercialización de envases y tapas plásticas; inyección y soplado.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 86,
      "name": "Productos Ávila",
      "industry": "Manufactura",
      "subindustry": "Alimentos",
      "location": "Zapopan",
      "website": "https://productosavila.com/",
      "description": "Produce alimentos procesados y productos de consumo masivo.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 87,
      "name": "Celofanfan",
      "industry": "Manufactura",
      "subindustry": "Empaque flexible",
      "location": "Guadalajara",
      "website": "https://www.celofanfan.com.mx/",
      "description": "Fabrica películas de celofán, polipropileno y empaques flexibles para la industria.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 88,
      "name": "REFA 100",
      "industry": "Distribución",
      "subindustry": "Refacciones automotrices online",
      "location": "Tlaquepaque",
      "website": "https://refa100.com/",
      "description": "Refaccionaria online de productos para seguridad y protección del vehículo",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 89,
      "name": "Industrial Valadez",
      "industry": "Manufactura",
      "subindustry": "Productos metálicos",
      "location": "Guadalajara",
      "website": "https://www.industrialvaladezsadecv.com/",
      "description": "Fabrica componentes y productos metálicos para aplicaciones industriales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 90,
      "name": "Botellas y Tapas Cristal",
      "industry": "Distribución",
      "subindustry": "Envases plásticos",
      "location": "Guadalajara",
      "website": "https://www.botellasytapascristal.com.mx/",
      "description": "Distribuye botellas, tapas y envases para las industrias alimenticia, farmacéutica y química.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 91,
      "name": "La Fiesta Reynoso",
      "industry": "Distribución",
      "subindustry": "Envases y suministros industriales",
      "location": "Guadalajara",
      "website": "https://www.comercializadorareyso.com/",
      "description": "Comercializa envases, empaques e insumos para la industria y el comercio.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 92,
      "name": "Rogmar",
      "industry": "Distribución",
      "subindustry": "Mayoreo de abarrotes",
      "location": "Guadalajara",
      "website": "https://www.rogmarmenudeo.com/",
      "description": "Distribuye productos de abarrotes y consumo para comercios y clientes mayoristas.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 93,
      "name": "Plásticos Las Brisas",
      "industry": "Manufactura",
      "subindustry": "Productos plásticos",
      "location": "Guadalajara",
      "website": "https://www.plasticoslasbrisas.com.mx/",
      "description": "Fabrica artículos y componentes plásticos para aplicaciones industriales y comerciales.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 94,
      "name": "Silky Industrial",
      "industry": "Manufactura",
      "subindustry": "Productos de limpieza industrial",
      "location": "Guadalajara",
      "website": "https://www.silkyindustrial.com.mx/",
      "description": "Fabrica y comercializa productos químicos para limpieza y mantenimiento industrial.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 95,
      "name": "Siwa Uniformes",
      "industry": "Manufactura",
      "subindustry": "Uniformes industriales",
      "location": "Tlajomulco",
      "website": "https://www.siwauniformes.com.mx/",
      "description": "Diseña, fabrica y comercializa uniformes corporativos, industriales y de seguridad.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 96,
      "name": "Botellas Guadalajara",
      "industry": "Distribución",
      "subindustry": "Envases plásticos",
      "location": "Guadalajara",
      "website": "https://www.botellasguadalajara.com.mx/",
      "description": "Distribuye botellas, envases y accesorios para las industrias alimenticia, cosmética y química.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 97,
      "name": "Servitornillos SIMA",
      "industry": "Distribución",
      "subindustry": "Fijación industrial",
      "location": "Guadalajara",
      "website": "https://www.ventadetornillosytuercasgdl.com/",
      "description": "Distribuye tornillos, tuercas, birlos y sistemas de fijación para la industria y la construcción.",
      "method": "Llamada",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 98,
      "name": "SuperRuedas",
      "industry": "Distribución",
      "subindustry": "Distribución de llantas y servicios para flotillas",
      "location": "Guadalajara",
      "website": "https://www.superruedas.com.mx/index.php",
      "description": "Comercializa llantas, rines y servicios de mantenimiento para vehículos comerciales, transporte pesado y flotillas.",
      "method": "No Contactado",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 99,
      "name": "El Rey Del Tornillo Guadalajara",
      "industry": "Distribución",
      "subindustry": "Tornillería, fijación y herramientas",
      "location": "Guadalajara",
      "website": "https://elreydeltornillo.com/",
      "description": "Mayorista de tornillería y herramientas de fijación que fue  fundada en 1997 y actualmente tiene 9 sucursales.",
      "method": "Rebotado",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 100,
      "name": "Componentes Electrónicos de Occidente SA de CV",
      "industry": "Distribución",
      "subindustry": "Identificación, marcado y etiquetado",
      "location": "Zapopan",
      "website": "https://ceo-mex.com/",
      "description": "Soluciones de identificación, marcado y etiquetado de productos que fue fundada en 2006.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 101,
      "name": "Terminados Plásticos de Occidente (TEPOSA)",
      "industry": "Manufactura",
      "subindustry": "Empaque flexible",
      "location": "Tlajomulco",
      "website": "https://teposa.com/",
      "description": "Fabrica productos plásticos termoformados y soluciones de empaque.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 102,
      "name": "Copiroyal Printcenter",
      "industry": "Distribución",
      "subindustry": "Copiadoras, consumibles y refacciones",
      "location": "Tlaquepaque",
      "website": "https://copiroyalcapital.com/",
      "description": "Venta de equipos Ricoh/Canon, tóner, refacciones y reparación de copiadoras",
      "method": "Llamada",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 103,
      "name": "Prakticaja",
      "industry": "Manufactura",
      "subindustry": "Cajas y empaques de cartón",
      "location": "Guadalajara",
      "website": "https://prakticaja.wixsite.com/website",
      "description": "Fabricación y comercialización de cajas y empaques de cartón corrugado.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 104,
      "name": "VEEN",
      "industry": "Distribución",
      "subindustry": "Agua alcalina y embotellada",
      "location": "Tlaquepaque",
      "website": "https://veen.com.mx/",
      "description": "Marca de agua alcalina y venta de productos de hidratación.",
      "method": "Llamada",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 105,
      "name": "TMC Hidráulicos",
      "industry": "Distribución",
      "subindustry": "Hidráulica industrial",
      "location": "Guadalajara",
      "website": "https://www.tmchidraulicos.com/",
      "description": "Distribuye mangueras, conexiones y componentes para sistemas hidráulicos.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 106,
      "name": "Naturex",
      "industry": "Manufactura",
      "subindustry": "Suplementos alimenticios",
      "location": "Tlaquepaque",
      "website": "https://www.naturex.com.mx/",
      "description": "Desarrollo, fabricación y comercialización de suplementos; pertenece a grupo Maver.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 107,
      "name": "CEPAMOSA S.A. de C.V.",
      "industry": "Distribución",
      "subindustry": "Montacargas, renta, venta y mantenimiento",
      "location": "Tlaquepaque",
      "website": "http://www.cepamosa.com",
      "description": "Distribuidor de Clark. Venta, renta, refacciones y servicio de montacargas que fue fundada en 1988.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 108,
      "name": "Tornillos Especializados de Occidente",
      "industry": "Distribución",
      "subindustry": "Ferretería y suministros industriales",
      "location": "Zapopan",
      "website": "https://www.tornillosespecializados.com/",
      "description": "Distribuye tornillos, fijaciones y sistemas de sujeción para la industria.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 109,
      "name": "Refaccionaria Mario García S.A. de C.V.",
      "industry": "Distribución",
      "subindustry": "Refacciones automotrices online",
      "location": "Guadalajara",
      "website": "http://www.refmariogarcia.com",
      "description": "Refaccionaria de productos para motor automotriz",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 110,
      "name": "Alfa uniformes",
      "industry": "Manufactura",
      "subindustry": "Uniformes empresariales",
      "location": "Tlaquepaque",
      "website": "https://alfauniformes.com/",
      "description": "Manufactura y distribución de uniformes para el trabajo o empresariales",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 111,
      "name": "Piruche Vasos de Papel",
      "industry": "Distribución",
      "subindustry": "Desechables y Vasos de papel",
      "location": "Guadalajara",
      "website": "https://pituche.com/?utm_source=google&utm_medium=cpc&utm_campaign=INPD-MAXPER&utm_content=General-2&gad_source=1&gad_campaignid=21493642458&gbraid=0AAAAADExx4S_1JJQ3bP9gp_BgAd5TsAEU&gclid=CjwKCAjwpK3SBhASEiwAtV1SPNW-XrmBhVW4CDWlFBTsE2R7ExJb1MgzkqjH7or7icFuK5LcJU1miRoCnCkQAvD_BwE",
      "description": "Desechables biodegradables, vasos y productos para alimentos",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 112,
      "name": "ACERO SUECO PALME",
      "industry": "Distribución",
      "subindustry": "Aceros especiales y panel aluminio compuesto",
      "location": "Tlaquepaque",
      "website": "https://ccagrupo.com/projects/acero-sueco-palme/",
      "description": "Comercialización de aceros especiales; fundada por René y Ramón Palme Bhen en 1960.",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 113,
      "name": "DIMEO Apparel Group",
      "industry": "Distribución",
      "subindustry": "Textil y Apparel",
      "location": "Guadalajara",
      "website": "https://dimeo.mx/",
      "description": "Distribución, fabricación, comercialización de prendas con +35 años de experiencia",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 114,
      "name": "Tornillos y Tuercas Medina",
      "industry": "Distribución",
      "subindustry": "Fijación industrial",
      "location": "Guadalajara",
      "website": "https://www.tornillosytuercasmedina.com/",
      "description": "Comercializa tornillos, tuercas y productos de fijación para clientes industriales y ferreteros.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 115,
      "name": "Poliflex sa de cv",
      "industry": "Manufactura",
      "subindustry": "Poliducto corrugado y accesorios eléctricos",
      "location": "Guadalajara",
      "website": "https://poliflex.com.mx/",
      "description": "Diseña, fabrica y distribuye tuberías corrugadas y accesorios no metálicos para instalaciones eléctricas",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 116,
      "name": "Ferman",
      "industry": "Distribución",
      "subindustry": "Fertilizantes y nutrición vegetal",
      "location": "Guadalajara / Mexico",
      "website": "https://www.ferman.mx/",
      "description": "Empresa fundada en 1992 en Guadalajara; comercializa fertilizantes sólidos, solubles, foliares y mejoradores de suelo.",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 117,
      "name": "Somoldi",
      "industry": "Manufactura",
      "subindustry": "Moldes e inyección de plástico",
      "location": "Tlaquepaque",
      "website": "https://www.somoldi.com/",
      "description": "Empresa mexicana con +30 años en diseño/fabricación de moldes e inyección de plástico para automotriz, alimentos, farma, electrónica y consumo",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 118,
      "name": "Tubin",
      "industry": "Manufactura",
      "subindustry": "Tubería y conexiones plásticas",
      "location": "Guadalajara",
      "website": "https://www.tubin.com.mx/",
      "description": "Fabrica y comercializa sistemas de tubería y conexiones de PVC y CPVC para conducción de fluidos.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 119,
      "name": "NOROACEROS S.A. de C.V.",
      "industry": "Distribución",
      "subindustry": "Acero / Industrial",
      "location": "Tlaquepaque",
      "website": "https://www.noroaceros.com/",
      "description": "Distribución, servicio y fabricación de perfiles especiales",
      "method": "Llamada",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 120,
      "name": "Gobi | Productos y Artículos de Limpieza",
      "industry": "Distribución",
      "subindustry": "Artículos e insumos de limpieza",
      "location": "Tlaquepaque",
      "website": "https://www.gobi.com.mx/",
      "description": "Distribuidora de artículos de limpieza institucional; maneja marcas como Elite, Kimberly-Clark, Jofel, Gojo y Rubbermaid",
      "method": "Llamada",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 121,
      "name": "Alimentos Naturales Finos S.A. de C.V.",
      "industry": "Manufactura",
      "subindustry": "Alimentos y bebidas",
      "location": "Tlaquepaque",
      "website": "http://alina.com.mx/",
      "description": "Empresa mexicana enfocada en desarrollar e introducir productos naturales al mercado",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 122,
      "name": "Merka-trucks",
      "industry": "Distribución",
      "subindustry": "Autopartes / Distribución",
      "location": "Tlaquepaque",
      "website": "https://merka-trucks.com.mx/",
      "description": "Comercialización de accesorios, refacciones y tractopartes para transporte de carga",
      "method": "No Contactado",
      "firstContact": "2026-07-13",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 123,
      "name": "SITMA",
      "industry": "Manufactura",
      "subindustry": "Alcantarillas de plástico reciclado",
      "location": "Tlaquepaque",
      "website": "https://sitma.com.mx/",
      "description": "Sitma de Mesoamérica; productos industriales de plástico reciclado para infraestructura",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 124,
      "name": "Corporativo Mohema SA de CV",
      "industry": "Distribución",
      "subindustry": "Ingredientes / Químicos",
      "location": "Guadalajara",
      "website": "https://www.cosmos.com.mx/empresa/corporativo-mohema-gsrp.html",
      "description": "Comercialización de vitaminas, aminoácidos, excipientes, sales y materias primas especializadas",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 125,
      "name": "Uniformes Carmen",
      "industry": "Manufactura",
      "subindustry": "Textil",
      "location": "Guadalajara",
      "website": "https://uniformescarmen.com.mx/",
      "description": "Fabrica uniformes industriales, empresariales e institucionales.",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 126,
      "name": "Uniformes Lazzar Guadalajara México",
      "industry": "Manufactura",
      "subindustry": "Uniformes industriales y corporativos",
      "location": "Guadalajara",
      "website": "https://www.lazzarmexico.com/contacto/uniformes-guadalajara-jalisco/?utm_source=GMB&utm_medium=profile&utm_campaign=local_search",
      "description": "Fabricante mexicano de uniformes industriales, corporativos, ejecutivos, médicos y de seguridad. Cuenta con planta propia y distribución nacional",
      "method": "Correo",
      "firstContact": "2026-07-16",
      "response": "Rechazo",
      "status": "Declinado | No tienen interés en explorar una venta",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 127,
      "name": "Suelas Italia",
      "industry": "Manufactura",
      "subindustry": "Calzado",
      "location": "Guadalajara",
      "website": "https://suelas-italia.com/",
      "description": "Fabricación de suelas para calzado",
      "method": "Correo",
      "firstContact": "2026-07-08",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 128,
      "name": "Mederilab",
      "industry": "Manufactura",
      "subindustry": "Dispositivos médicos",
      "location": "Zapopan",
      "website": "https://www.mederilab.com/",
      "description": "Empresa dedicada al desarrollo y fabricación de material médico y productos para hospitales y distribuidores",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 129,
      "name": "LiderPlast (Soluciones en Envases Plásticos PET)",
      "industry": "Manufactura",
      "subindustry": "Plásticos",
      "location": "Guadalajara",
      "website": "https://liderplast.com/",
      "description": "Fabricación de envases PET para alimentos, bebidas, químicos y productos de consumo",
      "method": "Correo",
      "firstContact": "2026-07-07",
      "response": "Sin Respuesta",
      "status": "Sin respuesta",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 130,
      "name": "Standar Manufactura de Productos S.A. de C.V.",
      "industry": "Manufactura",
      "subindustry": "Productos industriales",
      "location": "Guadalajara",
      "website": "https://www.hotfrog.com.mx/company/1123369700560896",
      "description": "Empresa manufacturera enfocada en la fabricación de productos industriales para clientes B2B",
      "method": "Carta Presencial",
      "firstContact": "",
      "response": "Sin Respuesta",
      "status": "Pendiente",
      "information": "Pendiente",
      "nextStep": "N/A"
    },
    {
      "id": 131,
      "name": "Forzac",
      "industry": "Manufactura",
      "subindustry": "Concreto premezclado",
      "location": "Guadalajara",
      "website": "https://www.forzac.com.mx/es/",
      "description": "Fabricante de concreto premezclado y concretos especiales para proyectos de construcción e infraestructura.",
      "method": "Llamada",
      "firstContact": "2026-07-07",
      "response": "Interés",
      "status": "Interés confirmado | NDA firmado y pendiente recepción de información",
      "information": "Pendiente",
      "nextStep": "Seguimiento para recibir información"
    },
    {
      "id": 132,
      "name": "Kadled",
      "industry": "Manufactura",
      "subindustry": "Manufactura electrónica y tableros eléctricos",
      "location": "Guadalajara",
      "website": "https://www.kadled.mx/",
      "description": "Diseña y fabrica ensambles electrónicos, tableros eléctricos de baja tensión y soluciones de iluminación industrial para proyectos de infraestructura e industria.",
      "method": "Llamada",
      "firstContact": "2026-07-07",
      "response": "Rechazo",
      "status": "Declinado | No cumple con los criterios de búsqueda (ventas)",
      "information": "N/A",
      "nextStep": "N/A"
    },
    {
      "id": 133,
      "name": "Qualmex",
      "industry": "Distribución",
      "subindustry": "Distribución de hardware tecnológico y soluciones para automatización industrial y medios de pago",
      "location": "Guadalajara",
      "website": "https://www.qualmex.com/en",
      "description": "Distribuye e integra equipos tecnológicos para medios de pago, punto de venta (POS), cómputo industrial y soluciones de autoservicio para industrias como retail, transporte, vending y estacionamientos.",
      "method": "Reunion Presencial",
      "firstContact": "",
      "response": "Interés",
      "status": "Interés confirmado |  Pendiente llamada inicial",
      "information": "Pendiente",
      "nextStep": "Coordinar llamada inicial"
    },
    {
      "id": 134,
      "name": "Empresa de válvulas industriales",
      "industry": "Distribución",
      "subindustry": "Fabricación de válvulas industriales y equipos para control de fluidos",
      "location": "Guadalajara",
      "website": "",
      "description": "Se trata de una empresa mexicana especializada en el abastecimiento de válvulas industriales manuales, automatizadas y de control para distintas aplicaciones industriales. La compañía ofrece soluciones para válvulas de mariposa, alto rendimiento, triple excentricidad, bola, compuerta, cuchillas, globo, check, pistón, reguladoras de presión, reguladoras de flujo, diafragma, chorro divergente, pellizco, aguja, seguridad y alivio, higiénicas sanitarias y diversoras.",
      "method": "Llamada",
      "firstContact": "",
      "response": "Interés",
      "status": "Interés confirmado |  Pendiente firmar NDA",
      "information": "Pendiente",
      "nextStep": "Firmar NDA y solicitar información"
    }
  ]
};